PROGRAM MPICUDAAWARE

USE CUDAFOR
USE MPL_MODULE, ONLY : MPL_SEND, MPL_RECV, MPL_BARRIER, MPL_INIT, MPL_END, MPL_WAIT, &
                     & JP_NON_BLOCKING_STANDARD

IMPLICIT NONE

INCLUDE 'mpif.h'

INTEGER, ALLOCATABLE, DEVICE :: D_SEND (:), D_RECV (:)
INTEGER, ALLOCATABLE         :: H_SEND (:), H_RECV (:)

INTEGER :: IREQ_RECV, IREQ_SEND
INTEGER :: ISTATUS (MPI_STATUS_SIZE)
INTEGER :: ISIZE, IERROR
INTEGER :: IRANK, IRANKP, IRANKN

CALL MPL_INIT ()

CALL MPI_COMM_RANK (MPI_COMM_WORLD, IRANK, IERROR)
CALL MPI_COMM_SIZE (MPI_COMM_WORLD, ISIZE, IERROR)

ALLOCATE (D_RECV (1))
ALLOCATE (D_SEND (1))
ALLOCATE (H_RECV (1))
ALLOCATE (H_SEND (1))

D_SEND = IRANK
D_RECV = -1

IRANKP = MODULO (IRANK-1, ISIZE)
IRANKN = MODULO (IRANK+1, ISIZE)

PRINT *, " DEVICE DATA "

CALL MPL_RECV (D_RECV, KSOURCE=IRANKP+1, KTAG=1001, KCOMM=MPI_COMM_WORLD, KREQUEST=IREQ_RECV, &
             & KMP_TYPE=JP_NON_BLOCKING_STANDARD)

CALL MPL_BARRIER ()

CALL MPL_SEND (D_SEND, KDEST=IRANKN+1, KTAG=1001, KCOMM=MPI_COMM_WORLD, KREQUEST=IREQ_SEND, &
             & KMP_TYPE=JP_NON_BLOCKING_STANDARD)

CALL MPL_WAIT (IREQ_RECV)
CALL MPL_WAIT (IREQ_SEND)

H_RECV = D_RECV
PRINT *, IRANK, " ==> ", H_RECV (:)

H_SEND = IRANK
H_RECV = -1

PRINT *, " HOST DATA "

CALL MPL_RECV (H_RECV, KSOURCE=IRANKP+1, KTAG=1001, KCOMM=MPI_COMM_WORLD, KREQUEST=IREQ_RECV, &
             & KMP_TYPE=JP_NON_BLOCKING_STANDARD)

CALL MPL_BARRIER ()

CALL MPL_SEND (H_SEND, KDEST=IRANKN+1, KTAG=1001, KCOMM=MPI_COMM_WORLD, KREQUEST=IREQ_SEND, &
             & KMP_TYPE=JP_NON_BLOCKING_STANDARD)

CALL MPL_WAIT (IREQ_RECV)
CALL MPL_WAIT (IREQ_SEND)

PRINT *, IRANK, " ==> ", H_RECV (:)

H_SEND = IRANK
H_RECV = -1

PRINT *, " HOST DATA (USE_DEVICE) "

!$ACC DATA COPY (H_RECV, H_SEND)

!$ACC HOST_DATA USE_DEVICE (H_RECV)
CALL MPL_RECV (H_RECV, KSOURCE=IRANKP+1, KTAG=1001, KCOMM=MPI_COMM_WORLD, KREQUEST=IREQ_RECV, &
             & KMP_TYPE=JP_NON_BLOCKING_STANDARD)
!$ACC END HOST_DATA

CALL MPL_BARRIER ()

!$ACC HOST_DATA USE_DEVICE (H_SEND)
CALL MPL_SEND (H_SEND, KDEST=IRANKN+1, KTAG=1001, KCOMM=MPI_COMM_WORLD, KREQUEST=IREQ_SEND, &
             & KMP_TYPE=JP_NON_BLOCKING_STANDARD)
!$ACC END HOST_DATA

CALL MPL_WAIT (IREQ_RECV)
CALL MPL_WAIT (IREQ_SEND)

!$ACC END DATA

PRINT *, IRANK, " ==> ", H_RECV (:)

DEALLOCATE (D_SEND)
DEALLOCATE (D_RECV)
DEALLOCATE (H_SEND)
DEALLOCATE (H_RECV)

PRINT *, "FINALIZE"

CALL MPL_END
 
END PROGRAM MPICUDAAWARE
