PROGRAM testbug

use cublas

IMPLICIT NONE

DOUBLE PRECISION, ALLOCATABLE :: PSPDIVG1(:,:)

ALLOCATE (PSPDIVG1(100,200))
PSPDIVG1(:,:)=1.0D0

CALL SPCSI(PSPDIVG1)

CONTAINS

SUBROUTINE SPCSI(PSPDIVG)

use cublas

IMPLICIT NONE
 
DOUBLE PRECISION  ,INTENT(INOUT) :: PSPDIVG(:,:) 

INTEGER*4,PARAMETER::KEND=200
INTEGER*4,PARAMETER::KSTA=100
INTEGER*4,PARAMETER::NFLEVG=100
INTEGER*4,PARAMETER::NSMAX=200
INTEGER*4,PARAMETER::KM=1
INTEGER*4::ISPCOL

DOUBLE PRECISION::COEFFS(NFLEVG,NFLEVG)
DOUBLE PRECISION :: ZSDIV  (NFLEVG,KSTA:KEND)

ISPCOL=KEND-KSTA+1
COEFFS(:,:)=1.0D0
ZSDIV(:,:)=2.0D0

!$acc data copy(pspdivg,COEFFS,ZSDIV)

!!!replacing as in the three lines below PSPDIVG by ZSDIV removes the bug
!!!$acc host_data use_device(COEFFS,ZSDIV)
!!CALL cublasDgemm ('N','N',NFLEVG,ISPCOL,NFLEVG,1.0D0, &
!!  & COEFFS,NFLEVG,ZSDIV(:,:),NFLEVG,0.0D0,ZSDIV(:,KSTA:KEND),NFLEVG)
!!!$acc end host_data

!$acc host_data use_device(COEFFS,ZSDIV,PSPDIVG)
CALL cublasDgemm ('N','N',NFLEVG,ISPCOL,NFLEVG,1.0D0, &
  & COEFFS,NFLEVG,ZSDIV(1,1),NFLEVG,0.0D0,PSPDIVG(1,KSTA),NFLEVG)
!$acc end host_data

!$acc end data 

END SUBROUTINE SPCSI

END 

